SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[Dallas2023]'
GO
ALTER TABLE [dbo].[Dallas2023] DROP CONSTRAINT [DF__Dallas202__Headi__6EF57B66]
GO
PRINT N'Dropping [dbo].[Dallas2023]'
GO
DROP TABLE [dbo].[Dallas2023]
GO

