SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[Dallas2023]'
GO
CREATE TABLE [dbo].[Dallas2023]
(
[HeadingToTheSuperBowl] [bit] NULL CONSTRAINT [DF__Dallas202__Headi__6EF57B66] DEFAULT ((1))
)
GO

